name: Build Docs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: JS Docs
        run: |
          git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm install
          npm install -g jsdoc
          jsdoc -c jsdoc.json
          git add docs -f
          git commit -m "Update JS Docs [WORKFLOW]"
          git push origin main